import { useCallback, useEffect, useMemo, useState } from 'react';
import { getFindings, getRecommendations, decideRecommendation, type Finding, type Recommendation } from '@/services/api';
import { Head, Box, Err, Pager, chip, sev, msg, sel } from '@/pages/live-ui';

export default function LiveRecommendations() {
  const size = 8;
  const [recs, setRecs] = useState<Recommendation[]>([]);
  const [fs, setFs] = useState<Finding[]>([]);
  const [st, setSt] = useState('Pending');
  const [page, setPage] = useState(1);
  const [busy, setBusy] = useState<number | null>(null);
  const [err, setErr] = useState<string | null>(null);
  const load = useCallback(() => {
    Promise.all([getRecommendations(), getFindings()]).then(([r, f]) => { setRecs(r); setFs(f); }).catch((e) => setErr(msg(e)));
  }, []);
  useEffect(() => { load(); }, [load]);
  const byId = useMemo(() => new Map(fs.map((f) => [f.id, f])), [fs]);
  const rows = recs.filter((r) => st === 'All' || r.status === st).sort((a, b) => b.risk_reduction - a.risk_reduction);
  const pageRows = rows.slice((page - 1) * size, page * size);
  const act = async (id: number, what: 'accept' | 'reject') => {
    setBusy(id);
    try { setErr(null); await decideRecommendation(id, what); load(); } catch (e) { setErr(msg(e)); } finally { setBusy(null); }
  };
  return (
    <>
      <Head eyebrow="REMEDIATION / LEAST PRIVILEGE" title="Recommendations" sub="Narrowed grants generated by the audit. Accept and Reject are saved in the backend."
        actions={<select style={sel} value={st} onChange={(e) => { setSt(e.target.value); setPage(1); }} aria-label="Filter by status">{['Pending', 'Accepted', 'Rejected', 'All'].map((s) => <option key={s}>{s}</option>)}</select>} />
      <Err m={err} />
      <p className="dim">{rows.length} recommendations shown, sorted by risk reduction</p>
      {pageRows.map((r) => {
        const f = byId.get(r.finding_id);
        return (
          <Box key={r.id}>
            <div style={{ display: 'flex', justifyContent: 'space-between', gap: 10, flexWrap: 'wrap' }}>
              <b>{f ? f.user_id : 'account'} <span className="dim">{f ? f.finding_type.replaceAll('_', ' ') : ''}</span></b>
              <span>{f && sev(f.severity)} <span className={'badge badge-' + (r.status === 'Accepted' ? 'green' : r.status === 'Rejected' ? 'red' : 'amber')}>{r.status}</span></span>
            </div>
            <div style={{ margin: '8px 0' }}>
              <small className="dim">CURRENT</small><div>{chip(r.current_action, '#ff4757')} {chip('on ' + r.current_resource, '#ff4757')}</div>
              <small className="dim">RECOMMENDED</small>
              <div>{r.recommended_action.split(',').map((t) => t.trim()).filter(Boolean).map((t) => chip(t, '#00d68f'))} {chip('on ' + r.recommended_resource, '#00d68f')}</div>
            </div>
            <p className="dim">{r.reason}</p>
            <p>Risk reduction <b>{r.risk_reduction}%</b> | confidence <b>{r.confidence}%</b></p>
            {r.status === 'Pending' && (
              <div style={{ display: 'flex', gap: 8 }}>
                <button className="btn btn-primary" disabled={busy === r.id} onClick={() => act(r.id, 'accept')}>Accept</button>
                <button className="btn btn-secondary" disabled={busy === r.id} onClick={() => act(r.id, 'reject')}>Reject</button>
              </div>
            )}
          </Box>
        );
      })}
      <Pager page={page} total={rows.length} size={size} set={setPage} />
    </>
  );
}