import { useEffect, useMemo, useRef, useState } from 'react';
import './accessshield.css';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import { ErrorBoundary } from '@/components/error-boundary';
import { Toaster } from '@/components/ui/toaster';
import { TooltipProvider } from '@/components/ui/tooltip';
import NotFound from '@/pages/not-found';
import Landing from '@/pages/landing';
import SignIn from '@/pages/sign-in';
import AccountsPage from '@/pages/accounts';
import AccountPage, { BackendStatus } from '@/pages/account';
import LiveScenario from '@/pages/live-scenario';
import LiveLogs from '@/pages/live-logs';
import LivePolicies from '@/pages/live-policies';
import LiveRecommendations from '@/pages/live-recs';
import LiveEvidence from '@/pages/live-evidence';
import LiveDiff from '@/pages/live-diff';
import LiveReports from '@/pages/live-reports';
import LiveSimulator from '@/pages/live-simulator';
import { isSignedIn, signOut, currentUserEmail } from '@/lib/auth';
import { runAudit, getFindings, type AuditResult, type Finding as ApiFinding } from '@/services/api';
import { Link, Route, Router as WouterRouter, Switch, useLocation } from 'wouter';
import {
  Activity, AlertTriangle, ArrowRight, ArrowUpRight, Bell, Check, CheckCircle2, ChevronDown,
  ChevronLeft, ChevronRight, Clock3, CloudUpload, Download, FileBarChart2, FileCode2,
  FileDiff, FileSearch, Filter, Gauge, Globe2, History, Home, LockKeyhole, Menu,
  MoreHorizontal, Play, Plus, RefreshCw, Search, Settings, ShieldAlert, ShieldCheck, SlidersHorizontal,
  Sparkles, Upload, Users, X, Zap,
} from 'lucide-react';
import {
  Area, AreaChart, Bar, BarChart, CartesianGrid, Cell, Pie, PieChart, ResponsiveContainer, Tooltip as ChartTooltip,
  XAxis, YAxis,
} from 'recharts';

type Log = { id:number; time:string; user:string; service:string; action:string; resource:string; status:string; region:string };
type Policy = { id:string; name:string; user:string; service:string; actions:string[]; resource:string; risk:string; audited:string; active:boolean };
type Finding = { id:string; severity:string; user:string; service:string; permission:string; resource:string; score:number; confidence:number; status:string; type:string; reason:string };
type Recommendation = { id:string; policyId:string; user:string; service:string; current:string[]; observed:string[]; recommended:string[]; resource:string; reason:string; reduction:number; confidence:number; status:string };
type State = { logs:Log[]; policies:Policy[]; findings:Finding[]; recommendations:Recommendation[]; eventsAdded:number; auditRuns:number; notifications:string[]; live?:AuditResult };

const users = ['Alice Chen','Marcus Reed','Priya Nair','Jordan Ellis','Sofia Martinez','Ethan Brooks','Ava Wilson','Noah Kim','Maya Patel','Liam Foster','Olivia Grant','Caleb Moore','Zoe Turner','Isaac Bell','Nina Shah','Leo Park','Amara Okafor','Theo Wright','Elena Rossi','Kai Nakamura','Grace Liu','Owen Price','Layla Hassan','Sam Rivera','Milo Bennett','Iris Morgan','Arjun Mehta','Chloe Davis','Ravi Shah','Nora Blake','Dev Patel','Mina Cho','Finn Carter','Sara Ahmed','Cole Brooks','Lena Fischer','Jules Kim','Aiden Ross','Build Service Role','Backup Service Role','Data Pipeline Role','Deployment Service Role','Asha Iyer'];
const services = ['S3','EC2','Lambda','RDS','IAM'];
const actionsByService:Record<string,string[]> = {
  S3:['GetObject','PutObject','ListBucket','DeleteObject'], EC2:['DescribeInstances','StartInstances','StopInstances','TerminateInstances'],
  Lambda:['InvokeFunction','GetFunction','UpdateFunctionCode','DeleteFunction'], RDS:['DescribeDBInstances','StartDBInstance','StopDBInstance'],
  IAM:['ListRoles','GetRole','PassRole','CreateAccessKey'],
};
const svcPrefix:Record<string,string> = {S3:'s3',EC2:'ec2',Lambda:'lambda',RDS:'rds',IAM:'iam'};
const resources:Record<string,string[]> = {S3:['company-data/*','analytics-archive/*','customer-uploads/*'],EC2:['web-prod-*','batch-worker-*','*'],Lambda:['payment-service','thumbnail-worker','*'],RDS:['prod-cluster-01','reporting-db','*'],IAM:['application-role/*','*']};
const severities = ['CRITICAL','HIGH','MEDIUM','LOW'];
const findingTypes = ['UNUSED_PERMISSION','OVERBROAD_PERMISSION','WILDCARD_ACTION','WILDCARD_RESOURCE','DESTRUCTIVE_PERMISSION','EXCESSIVE_SCOPE'];
const makeState = ():State => {
  const logs:Log[] = Array.from({length:18642},(_,i)=>{
    const service=services[i%5], action=actionsByService[service][service==='RDS'?0:Math.floor(i/5)%3];
    const day=new Date(Date.now()-((i%90)*86400000 + (i%24)*3600000));
    return {id:i+1,time:day.toISOString(),user:users[(i*7+Math.floor(i/4))%users.length],service,action,resource:resources[service][(i*3)%resources[service].length].replace('*',`object-${(i%31)+1}`),status:i%53===0?'DENIED':'SUCCESS',region:['us-east-1','us-west-2','eu-west-1','ap-southeast-2'][i%4]};
  });
  const observedByIdentity=new Map<string,Set<string>>();
  for(const log of logs){
    const key=`${log.user}|${log.service}`;
    if(!observedByIdentity.has(key))observedByIdentity.set(key,new Set());
    observedByIdentity.get(key)!.add(`${svcPrefix[log.service]}:${log.action}`);
  }
  const observedFor=(user:string,service:string)=>Array.from(observedByIdentity.get(`${user}|${service}`)??[]);
  const policies:Policy[]=Array.from({length:128},(_,i)=>{
    const service=services[i%5], prefix=svcPrefix[service], user=users[(i*5)%users.length];
    const observed=observedFor(user,service);
    const unused=actionsByService[service].map(action=>`${prefix}:${action}`).find(action=>!observed.includes(action));
    const actions=i%4===0?[`${prefix}:*`]:Array.from(new Set([...observed,...(unused?[unused]:[])]));
    return {id:`POL-${String(i+101).padStart(4,'0')}`,name:['CloudDataReadWrite','ComputeOperations','ServerlessRuntime','DatabaseObserver','IdentityProvisioner'][i%5]+(i>4?`-${Math.floor(i/5)+1}`:''),user,service,actions,resource:i%3===0?'*':resources[service][i%resources[service].length],risk:i%13===0?'Critical':i%4===0?'High':i%3===0?'Medium':'Low',audited:`${(i%27)+1}h ago`,active:true};
  });
  const findings:Finding[]=Array.from({length:76},(_,i)=>{
    const policy=policies[i%policies.length], service=policy.service, observed=observedFor(policy.user,service);
    const unusedAction=actionsByService[service].find(action=>!observed.includes(`${svcPrefix[service]}:${action}`))??actionsByService[service][actionsByService[service].length-1];
    const action=i===0?'DeleteObject':unusedAction, destructive=action.startsWith('Delete')||action==='TerminateInstances'||action==='CreateAccessKey';
    const permission=`${svcPrefix[service]}:${action}`;
    const severity=i<3?'CRITICAL':i<12?'HIGH':i<36?'MEDIUM':'LOW';
    const type=i===0?'UNUSED_PERMISSION':findingTypes[i%findingTypes.length];
    const status=i<12?'Open':i%17===0?'Resolved':i%13===0?'In review':'Open';
    return {id:`FND-${String(i+2401).padStart(5,'0')}`,severity,user:policy.user,service,permission,resource:policy.resource,score:Math.max(38,97-(i*11%58)),confidence:88+(i*7%12),status,type,reason:destructive?'Destructive capability is granted but has no matching access event in the 90-day analysis window.':'The permission is granted by policy, but no matching access event was observed during the analysis window.'};
  });
  const recommendations:Recommendation[]=Array.from({length:34},(_,i)=>{
    const p=policies[(i*3)%policies.length], observed=observedFor(p.user,p.service);
    return {id:`REC-${String(i+5101).padStart(5,'0')}`,policyId:p.id,user:p.user,service:p.service,current:p.actions,observed,recommended:observed,resource:p.resource==='*'?resources[p.service][0]:p.resource,reason:'Observed access supports a narrower action set and explicit resource boundary.',reduction:72+(i*7%25),confidence:89+(i*3%10),status:i%9===0?'Accepted':i%7===0?'Rejected':'Pending'};
  });
  return {logs,policies,findings,recommendations,eventsAdded:0,auditRuns:0,notifications:['3 high-risk findings require review','Nightly audit completed successfully','New evidence package is available']};
};
const loadState=():State=>{try{const raw=localStorage.getItem('asx-demo-state-v2');return raw?JSON.parse(raw) as State:makeState()}catch{return makeState()}};
const NAV=[
  {label:'Overview',path:'/',icon:Home},{label:'Access Logs',path:'/access-logs',icon:Activity},{label:'IAM Policies',path:'/policies',icon:FileCode2},
  {label:'Run Audit',path:'/audit',icon:Zap},{label:'Findings',path:'/findings',icon:ShieldAlert},{label:'Recommendations',path:'/recommendations',icon:Sparkles},
  {label:'Policy Diff',path:'/policy-diff',icon:FileDiff},{label:'Evidence',path:'/evidence',icon:FileSearch},{label:'Scenario Simulator',path:'/simulator',icon:Gauge},
  {label:'Reports',path:'/reports',icon:FileBarChart2},{label:'Account Analysis',path:'/accounts',icon:Users},{label:'Settings',path:'/settings',icon:Settings},
];
const qs=(s:string)=>document.querySelector(s) as HTMLElement|null;
const download=(filename:string,content:string,type='text/plain')=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([content],{type}));a.download=filename;a.click();URL.revokeObjectURL(a.href)};
function App(){return <QueryClientProvider client={new QueryClient()}><TooltipProvider><WouterRouter base={import.meta.env.BASE_URL.replace(/\/$/,'')}><Router/></WouterRouter><Toaster/></TooltipProvider></QueryClientProvider>}
void [LogsPage,PoliciesPage,RecommendationsPage,EvidencePage,DiffPage,SimulatorPage,ReportsPage];
const toFinding=(f:ApiFinding):Finding=>({id:f.id,severity:f.severity,user:f.user_id,service:f.service,permission:f.action,resource:f.resource,score:f.risk_score,confidence:f.confidence,status:f.status,type:f.finding_type,reason:f.description});
function Router(){const [loc,setLoc]=useLocation();const open=loc==='/welcome'||loc==='/sign-in';const ok=isSignedIn();useEffect(()=>{if(!open&&!ok)setLoc('/welcome')},[open,ok,setLoc]);if(loc==='/welcome')return <Landing/>;if(loc==='/sign-in')return <SignIn/>;if(!ok)return null;return <ErrorBoundary resetKey={loc}><Shell/></ErrorBoundary>}
function Shell(){
  const [location,setLocation]=useLocation(),[state,setState]=useState<State>(loadState),[search,setSearch]=useState(''),[toast,setToast]=useState(''),[notify,setNotify]=useState(false),[mobileNav,setMobileNav]=useState(false),[modal,setModal]=useState<{title:string;body:any}|null>(null),[environment,setEnvironment]=useState('Production');
  useEffect(()=>{localStorage.setItem('asx-demo-state-v2',JSON.stringify(state))},[state]);
  useEffect(()=>{if(!toast)return;const t=setTimeout(()=>setToast(''),3100);return()=>clearTimeout(t)},[toast]);
  const say=(s:string)=>setToast(s), update=(fn:(s:State)=>State)=>setState(old=>fn(old));
  const prevRuns=useRef(state.auditRuns);
  const syncLive=async(run:boolean)=>{try{let a:AuditResult|undefined;if(run)a=await runAudit();const f=await getFindings();update(s=>({...s,findings:f.map(toFinding),live:a??s.live}));if(a)say(`Audit completed: score ${a.least_privilege_score}, ${a.findings_count} findings`)}catch(e){say(e instanceof Error?e.message:'Backend unreachable')}};
  useEffect(()=>{syncLive(true)},[]);
  useEffect(()=>{if(state.auditRuns>prevRuns.current)syncLive(true);prevRuns.current=state.auditRuns},[state.auditRuns]);
  const page=NAV.find(n=>n.path===location)?.label??'Overview';
  const openFinding=(f:Finding)=>{setModal({title:`Finding ${f.id}`,body:<FindingDetail finding={f} state={state} goEvidence={()=>{setModal(null);setLocation('/evidence')}}/>})};
  const context={state,update,say,setModal,openFinding,setLocation,search};
  const pageMap:Record<string,any>={'/':<Overview {...context}/>,'/access-logs':<LiveLogs/>,'/policies':<LivePolicies/>,'/audit':<AuditPage {...context}/>,'/findings':<FindingsPage {...context}/>,'/recommendations':<LiveRecommendations/>,'/policy-diff':<LiveDiff/>,'/evidence':<LiveEvidence/>,'/simulator':<LiveSimulator/>,'/reports':<LiveReports/>,'/accounts':<AccountsPage/>,'/account':<AccountPage/>,'/settings':<SettingsPage {...context}/>};
  return <div className="app-shell min-h-[100dvh] text-[#f5f9ff]">
    <aside className={`sidebar no-print ${mobileNav?'sidebar-open':''}`}>
      <div className="brand"><img src="/accessshield-mark.png" alt="AccessShield shield mark" data-testid="img-brand-mark"/><div><b>ACCESS<span>SHIELD</span> X</b><small>INTELLIGENT IAM AUDITOR</small></div><button aria-label="Close navigation" className="mobile-close" onClick={()=>setMobileNav(false)} data-testid="button-close-nav"><X size={17}/></button></div>
      <div className="side-label">WORKSPACE</div><nav className="nav-list">{NAV.map(n=>{const Icon=n.icon;return <Link href={n.path} key={n.path} onClick={()=>setMobileNav(false)} className={`nav-item ${location===n.path?'active':''}`} data-testid={`nav-${n.path.replace('/','')||'overview'}`}><Icon size={17}/><span>{n.label}</span>{n.path==='/findings'&&<em>{state.findings.filter(f=>f.status==='Open').length}</em>}</Link>})}</nav>
      <div className="sidebar-bottom"><div className="tenant-chip"><div className="tenant-logo">N</div><div><b>Northstar Labs</b><small>Enterprise workspace</small></div><MoreHorizontal size={16}/></div><div className="side-status"><span className="live-dot"/><span>All systems operational</span></div><small className="version">ACCESS SHIELD X <span>v2.8.1</span></small></div>
    </aside>
    {mobileNav&&<button className="nav-scrim" onClick={()=>setMobileNav(false)} aria-label="Close menu" data-testid="button-nav-scrim"/>}
    <main className="main-shell">
      <header className="topbar no-print"><button className="mobile-menu" aria-label="Open navigation" onClick={()=>setMobileNav(true)} data-testid="button-open-nav"><Menu size={19}/></button>
        <div className="crumb"><span>Workspace</span><span className="crumb-slash">/</span><b>{page}</b></div>
        <div className="top-actions"><label className="global-search"><Search size={15}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search policies, users, findings..." data-testid="input-global-search"/><kbd>⌘ K</kbd></label>
          <div className="environment"><Globe2 size={15}/><select value={environment} onChange={e=>setEnvironment(e.target.value)} aria-label="Environment selector" data-testid="select-environment"><option>Production</option><option>Staging</option><option>Development</option></select><ChevronDown size={13}/></div>
          <BackendStatus/>
          <div className="notification-wrap"><button className="icon-button" aria-label="Notifications" onClick={()=>setNotify(!notify)} data-testid="button-notifications"><Bell size={17}/><i/></button>{notify&&<div className="notification-pop panel"><div className="pop-head">Notifications <button onClick={()=>{update(s=>({...s,notifications:[]}));say('Notifications cleared')}} data-testid="button-clear-notifications">Clear</button></div>{state.notifications.length?state.notifications.map((x,i)=><p key={x}><span className="live-dot"/>{x}</p>):<p className="dim">You're all caught up.</p>}</div>}</div>
          <button className="btn btn-secondary" aria-label="Sign out" onClick={()=>{signOut();setLocation('/welcome')}} data-testid="button-sign-out"><LockKeyhole size={15}/>Sign out</button><div className="profile" role="button" tabIndex={0} style={{cursor:'pointer'}} onClick={()=>setLocation('/account')}><div className="avatar">AC</div><div><b>{currentUserEmail()??'Analyst'}</b><small>Security analyst</small></div><ChevronDown size={13}/></div>
        </div>
      </header>
      <div className="content-area">{pageMap[location]??<NotFound/>}</div>
      <footer className="app-footer no-print"><span>AccessShield X <i/> Least privilege, continuously verified</span><span>Last sync <b>just now</b> <i/> Region <b>us-east-1</b></span></footer>
    </main>
    {toast&&<div className="toast" role="status" data-testid="status-toast"><CheckCircle2 size={17}/>{toast}</div>}
    {modal&&<Modal title={modal.title} close={()=>setModal(null)}>{modal.body}</Modal>}
  </div>
}

type Ctx={state:State;update:(fn:(s:State)=>State)=>void;say:(s:string)=>void;setModal:(m:{title:string;body:any}|null)=>void;openFinding:(f:Finding)=>void;setLocation:(l:string)=>void;search:string};
function PageHead({eyebrow,title,subtitle,actions}:{eyebrow:string;title:string;subtitle:string;actions?:any}){return <div className="page-head fade-in"><div><div className="eyebrow">{eyebrow}</div><h1>{title}</h1><p>{subtitle}</p></div>{actions&&<div className="head-actions">{actions}</div>}</div>}
function Button({children,onClick,kind='secondary',icon,disabled=false,testId}:{children:any;onClick?:()=>void;kind?:'primary'|'secondary'|'quiet'|'danger';icon?:any;disabled?:boolean;testId?:string}){return <button disabled={disabled} onClick={onClick} className={`btn btn-${kind}`} data-testid={testId}>{icon}{children}</button>}
function Panel({children,title,sub,action,className=''}:{children:any;title?:string;sub?:string;action?:any;className?:string}){return <section className={`panel panel-box ${className}`}>{(title||action)&&<div className="panel-head"><div>{title&&<h3>{title}</h3>}{sub&&<p>{sub}</p>}</div>{action}</div>}{children}</section>}
function Badge({children,tone='blue'}:{children:any;tone?:string}){return <span className={`badge badge-${tone}`}>{children}</span>}
function Metric({label,value,change,icon,tone='blue',testId}:{label:string;value:string|number;change?:string;icon:any;tone?:string;testId:string}){const Icon=icon;return <div className="metric panel" data-testid={testId}><div className="metric-top"><span>{label}</span><i className={`metric-icon ${tone}`}><Icon size={16}/></i></div><b>{value}</b><small>{change}</small></div>}
function TableWrap({children}:{children:any}){return <div className="table-scroll"><table>{children}</table></div>}
function Pager({page,setPage,total,size}:{page:number;setPage:(n:number)=>void;total:number;size:number}){const pages=Math.max(1,Math.ceil(total/size));return <div className="pager"><span>Showing <b>{total?((page-1)*size+1):0}–{Math.min(page*size,total)}</b> of <b>{total}</b> records</span><div><button disabled={page<=1} onClick={()=>setPage(page-1)} aria-label="Previous page" data-testid="button-page-previous"><ChevronLeft size={15}/></button><span>{page} / {pages}</span><button disabled={page>=pages} onClick={()=>setPage(page+1)} aria-label="Next page" data-testid="button-page-next"><ChevronRight size={15}/></button></div></div>}
function Modal({title,children,close}:{title:string;children:any;close:()=>void}){return <div className="modal-scrim" onMouseDown={e=>{if(e.target===e.currentTarget)close()}}><div className="modal panel" role="dialog" aria-modal="true"><div className="modal-head"><h2>{title}</h2><button onClick={close} aria-label="Close dialog" data-testid="button-modal-close"><X size={18}/></button></div>{children}</div></div>}
function BarLine({data,keys}:{data:any[];keys:{key:string;color:string}[]}){return <ResponsiveContainer width="100%" height="100%"><AreaChart data={data}><defs>{keys.map(k=><linearGradient key={k.key} id={`grad-${k.key}`} x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor={k.color} stopOpacity={.27}/><stop offset="95%" stopColor={k.color} stopOpacity={0}/></linearGradient>)}</defs><CartesianGrid stroke="#1b3152" strokeDasharray="3 5" vertical={false}/><XAxis dataKey="name" stroke="#61738d" tick={{fontSize:10}} axisLine={false} tickLine={false}/><YAxis stroke="#61738d" tick={{fontSize:10}} axisLine={false} tickLine={false}/><ChartTooltip contentStyle={{background:'#0a1428',border:'1px solid #1b3152',borderRadius:8,color:'#fff'}}/>{keys.map(k=><Area key={k.key} type="monotone" dataKey={k.key} stroke={k.color} strokeWidth={2} fill={`url(#grad-${k.key})`} activeDot={{r:3}}/>)}</AreaChart></ResponsiveContainer>}
function Overview({state,openFinding,setLocation}:Ctx){
 const risk=[{name:'Critical',value:state.findings.filter(x=>x.severity==='CRITICAL').length,color:'#ff4757'},{name:'High',value:state.findings.filter(x=>x.severity==='HIGH').length,color:'#ffb020'},{name:'Medium',value:state.findings.filter(x=>x.severity==='MEDIUM').length,color:'#168bff'},{name:'Low',value:state.findings.filter(x=>x.severity==='LOW').length,color:'#00d68f'}];
 const trends=Array.from({length:8},(_,i)=>({name:['Mar 04','Mar 08','Mar 12','Mar 16','Mar 20','Mar 24','Mar 28','Apr 01'][i],critical:Math.max(2,12-i+Math.floor(i/3)),high:19-i}));
 return <><PageHead eyebrow="SECURITY POSTURE / PRODUCTION" title="IAM Security Overview" subtitle="Monitor permissions, detect excessive access, and continuously improve least privilege." actions={<><Button icon={<History size={15}/>} onClick={()=>setLocation('/audit')} testId="button-view-audits">Audit history</Button><Button kind="primary" icon={<Play size={15}/>} onClick={()=>setLocation('/audit')} testId="button-run-audit">Run new audit</Button></>}/>
 <div className="metrics-grid"><Metric label="IAM Policies" value={state.live?.policies_analyzed??state.policies.length} change="Across 5 cloud services" icon={FileCode2} testId="metric-total-policies"/><Metric label="Users" value={state.live?.users_analyzed??users.length} change="Identities in this audit" icon={Users} tone="cyan" testId="metric-user-count"/><Metric label="Access events" value={(state.live?.events_analyzed??state.logs.length).toLocaleString()} change="90-day observation window" icon={Activity} tone="purple" testId="metric-event-count"/><Metric label="Security findings" value={state.findings.length} change={`${risk[0].value+risk[1].value} high risk findings`} icon={ShieldAlert} tone="red" testId="metric-findings"/><Metric label="High Risk" value={risk[0].value+risk[1].value} change="Requires analyst review" icon={AlertTriangle} tone="amber" testId="metric-high-risk"/><Metric label="Least privilege" value={state.live?`${state.live.least_privilege_score}/100`:'-'} change="Live audit score" icon={ShieldCheck} tone="green" testId="metric-lp-score"/></div>
  <div className="overview-grid"><Panel title="Risk distribution" sub="All findings by severity" className="chart-panel"><div className="donut-layout"><div className="donut"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={risk} dataKey="value" innerRadius="67%" outerRadius="88%" paddingAngle={3} stroke="none">{risk.map(r=><Cell key={r.name} fill={r.color}/>)}</Pie><ChartTooltip contentStyle={{background:'#0a1428',border:'1px solid #1b3152',borderRadius:8}}/></PieChart></ResponsiveContainer><div className="donut-center"><b>{risk.reduce((a,b)=>a+b.value,0)}</b><small>TOTAL</small></div></div><div className="legend-list">{risk.map(r=><div key={r.name}><i style={{background:r.color}}/><span>{r.name}</span><b>{r.value}</b></div>)}</div></div></Panel>
 <Panel title="Permission usage" sub="Granted vs observed actions"><div className="usage-chart"><ResponsiveContainer width="100%" height="100%"><BarChart data={[{name:'Unused',count:state.findings.filter(f=>f.type==='UNUSED_PERMISSION').length},{name:'Overbroad',count:state.findings.filter(f=>f.type==='OVERBROAD_PERMISSION').length},{name:'Wildcard',count:state.findings.filter(f=>f.type.startsWith('WILDCARD')).length}]} layout="vertical" margin={{left:8,right:16}}><CartesianGrid stroke="#1b3152" strokeDasharray="3 5" horizontal={false}/><XAxis type="number" hide/><YAxis type="category" dataKey="name" stroke="#8b9bb4" tick={{fontSize:11}} axisLine={false} tickLine={false}/><ChartTooltip contentStyle={{background:'#0a1428',border:'1px solid #1b3152',borderRadius:8}}/><Bar dataKey="count" radius={[0,4,4,0]}>{[0,1,2].map((n)=><Cell key={n} fill={['#00d68f','#ffb020','#6c5ce7'][n]}/>)}</Bar></BarChart></ResponsiveContainer></div><div className="usage-key"><span><i className="green-dot"/>Unused</span><span><i className="amber-dot"/>Overbroad</span><span><i className="purple-dot"/>Wildcard</span></div></Panel>
 <Panel title="Risk trend" sub="Finding activity · last 30 days" action={<button className="text-link" onClick={()=>setLocation('/findings')} data-testid="link-all-findings">View findings <ArrowRight size={13}/></button>} className="trend-panel"><div className="trend-chart"><BarLine data={trends} keys={[{key:'critical',color:'#ff4757'},{key:'high',color:'#ffb020'}]}/></div><div className="trend-foot"><span><i className="red-dot"/>Critical</span><span><i className="amber-dot"/>High</span><b>↓ 18.4% <small>vs prior period</small></b></div></Panel>
  <Panel title="Findings by service" sub="Distribution across cloud services"><div className="service-bars">{services.map(s=>{const n=state.findings.filter(f=>f.service===s).length;return <div className="service-row" key={s}><span>{s}</span><div><i style={{width:`${n*4}%`}}/></div><b>{n}</b></div>})}</div><div className="panel-foot"><span>5 monitored services</span><Badge tone="green">All monitored</Badge></div></Panel></div>
 <Panel title="Recent findings" sub="Prioritized items needing analyst attention" action={<Button onClick={()=>setLocation('/findings')} testId="button-open-findings">All findings <ArrowUpRight size={14}/></Button>} className="recent-table"><TableWrap><thead><tr><th>SEVERITY</th><th>FINDING</th><th>IDENTITY</th><th>SERVICE</th><th>RISK</th><th>STATUS</th><th/></tr></thead><tbody>{state.findings.slice(0,6).map(f=><tr key={f.id} data-testid={`row-recent-finding-${f.id}`}><td><Badge tone={f.severity.toLowerCase()}>{f.severity}</Badge></td><td><button className="table-primary" onClick={()=>openFinding(f)} data-testid={`button-finding-detail-${f.id}`}>{f.permission}</button><small className="table-sub">{f.type.replaceAll('_',' ')}</small></td><td>{f.user}</td><td>{f.service}</td><td><b>{f.score}</b><span className="muted"> / 100</span></td><td><Badge tone={f.status==='Resolved'?'green':'blue'}>{f.status}</Badge></td><td><button className="icon-button small" onClick={()=>openFinding(f)} aria-label={`Open ${f.id}`} data-testid={`button-open-${f.id}`}><ArrowUpRight size={14}/></button></td></tr>)}</tbody></TableWrap></Panel></>
}

function usePaged<T>(rows:T[],size=10){const [page,setPage]=useState(1);useEffect(()=>setPage(1),[rows]);return {page,setPage,items:rows.slice((page-1)*size,page*size),size}}
function LogsPage({state,update,say,search}:Ctx){
 const [user,setUser]=useState('All users'),[service,setService]=useState('All services'),[action,setAction]=useState('All actions'),[status,setStatus]=useState('All status');
 const rows=useMemo(()=>state.logs.filter(l=>(!search||`${l.user} ${l.service} ${l.action} ${l.resource}`.toLowerCase().includes(search.toLowerCase()))&&(user==='All users'||l.user===user)&&(service==='All services'||l.service===service)&&(action==='All actions'||l.action===action)&&(status==='All status'||l.status===status)),[state.logs,search,user,service,action,status]);
 const p=usePaged(rows,12);
  const loadDemo=()=>{update(s=>({...s,logs:makeState().logs,eventsAdded:0}));say('Demo access dataset loaded · 18,642 records')};
  const upload=(type:string,file?:File)=>{
    if(!file)return;
    const reader=new FileReader();
    reader.onload=()=>{
      if(type==='CSV'){
        const line=Math.max(0,String(reader.result).trim().split(/\r?\n/).length-1);
        if(!line){say(`${file.name} has no data rows`);return}
        const count=Math.min(line,100);
        update(s=>({...s,logs:[...s.logs,...Array.from({length:count},(_,i)=>({...s.logs[i%s.logs.length],id:Date.now()+i,time:new Date().toISOString()}))]}));
        say(`${file.name} imported · ${line} rows simulated`);
        return;
      }
      try{
        const data=JSON.parse(String(reader.result)),records=Array.isArray(data)?data:Array.isArray(data.records)?data.records:[data];
        const imported:Log[]=records.slice(0,100).map((row:any,i:number)=>{
          const service=services.find(value=>value.toLowerCase()===String(row.service??'').toLowerCase());
          const user=String(row.user??row.identity??'').trim(),action=String(row.action??'').trim(),resource=String(row.resource??'').trim();
          if(!service||!user||!resource||!actionsByService[service].includes(action))throw new Error('Each row needs user, service, action, and resource fields with a supported service action.');
          return {id:Date.now()+i,time:String(row.timestamp??row.time??new Date().toISOString()),user,service,action,resource,status:String(row.status??'SUCCESS').toUpperCase(),region:String(row.region??'us-east-1')};
        });
        if(!imported.length)throw new Error('The JSON file contains no access-log records.');
        update(s=>({...s,logs:[...imported,...s.logs]}));
        say(`${file.name} imported · ${imported.length} records added`);
      }catch(error){
        say(error instanceof Error?`JSON import failed · ${error.message}`:'JSON import failed · check the file format');
      }
    };
    reader.onerror=()=>say(`${file.name} could not be read`);
    reader.readAsText(file);
  };
 return <><PageHead eyebrow="TELEMETRY / ACCESS ACTIVITY" title="Access Logs" subtitle="Review observed cloud activity across identities, services, and resources." actions={<><label className="btn btn-secondary upload-btn"><Upload size={15}/>Upload CSV<input type="file" accept=".csv" onChange={e=>upload('CSV',e.target.files?.[0])} data-testid="input-upload-csv"/></label><label className="btn btn-secondary upload-btn"><Upload size={15}/>Upload JSON<input type="file" accept=".json" onChange={e=>upload('JSON',e.target.files?.[0])} data-testid="input-upload-json"/></label><Button kind="primary" onClick={loadDemo} icon={<RefreshCw size={15}/>} testId="button-load-demo-logs">Load demo dataset</Button></>}/>
  <div className="stat-strip"><div><small>RECORDS</small><b data-testid="text-log-record-count">{rows.length.toLocaleString()}</b></div><div><small>IDENTITIES</small><b>{users.length}</b></div><div><small>SERVICES</small><b>5</b></div><div><small>DATE RANGE</small><b>90 days</b></div><div className="stat-note"><span className="live-dot"/>Log pipeline healthy <span>·</span> Updated just now</div></div>
  <Panel className="data-panel"><div className="filters"><span><Filter size={14}/> Filter events</span><select value={user} onChange={e=>setUser(e.target.value)} data-testid="filter-log-user"><option>All users</option>{users.map(u=><option key={u}>{u}</option>)}</select><select value={service} onChange={e=>setService(e.target.value)} data-testid="filter-log-service"><option>All services</option>{services.map(u=><option key={u}>{u}</option>)}</select><select value={action} onChange={e=>setAction(e.target.value)} data-testid="filter-log-action"><option>All actions</option>{Array.from(new Set(state.logs.map(l=>l.action))).sort().map(a=><option key={a}>{a}</option>)}</select><select value={status} onChange={e=>setStatus(e.target.value)} data-testid="filter-log-status"><option>All status</option><option>SUCCESS</option><option>DENIED</option></select><span className="filter-spacer"/><span className="dim">{rows.length} events</span></div><TableWrap><thead><tr><th>TIMESTAMP</th><th>IDENTITY</th><th>SERVICE</th><th>ACTION</th><th>RESOURCE</th><th>STATUS</th><th>REGION</th></tr></thead><tbody>{p.items.map(l=><tr key={l.id} data-testid={`row-access-log-${l.id}`}><td className="mono">{new Date(l.time).toLocaleString()}</td><td><span className="user-cell"><i>{l.user.split(' ').map(x=>x[0]).join('')}</i>{l.user}</span></td><td>{l.service}</td><td className="mono">{svcPrefix[l.service]}:{l.action}</td><td className="mono">{l.resource}</td><td><Badge tone={l.status==='SUCCESS'?'green':'red'}>{l.status}</Badge></td><td>{l.region}</td></tr>)}</tbody></TableWrap><Pager page={p.page} setPage={p.setPage} total={rows.length} size={p.size}/></Panel></>
}
function PoliciesPage({state,update,say,setModal,search}:Ctx){
 const [q,setQ]=useState(''),[risk,setRisk]=useState('All risk'),[page,setPage]=useState(1);
 const rows=state.policies.filter(p=>(!search||`${p.name} ${p.user} ${p.id}`.toLowerCase().includes(search.toLowerCase()))&&(!q||`${p.name} ${p.user} ${p.id} ${p.service}`.toLowerCase().includes(q.toLowerCase()))&&(risk==='All risk'||p.risk===risk));
 const open=(policy:Policy)=>setModal({title:`Policy · ${policy.name}`,body:<div className="policy-detail"><div className="detail-meta"><Badge tone={policy.risk.toLowerCase()}>{policy.risk} risk</Badge><span>{policy.id}</span><span>Owner · {policy.user}</span></div><div className="code-block"><div className="code-head"><span><i/>JSON POLICY DOCUMENT</span><button onClick={()=>{navigator.clipboard?.writeText(JSON.stringify({Version:'2012-10-17',Statement:[{Effect:'Allow',Action:policy.actions,Resource:policy.resource}]},null,2));say('Policy JSON copied')}} data-testid="button-copy-policy">Copy JSON</button></div><pre>{JSON.stringify({Version:'2012-10-17',Statement:[{Effect:'Allow',Action:policy.actions,Resource:policy.resource}]},null,2)}</pre></div><div className="detail-summary"><div><small>SERVICE</small><b>{policy.service}</b></div><div><small>LAST AUDITED</small><b>{policy.audited}</b></div><div><small>PERMISSIONS</small><b>{policy.actions.length} statements</b></div></div><Button kind="primary" onClick={()=>{setModal(null)}} testId="button-close-policy-detail">Done</Button></div>});
  const create=()=>setModal({title:'Create IAM policy',body:<PolicyForm onSave={(name,user,service)=>{update(s=>({...s,policies:[{id:`POL-${Date.now()}`,name,user,service,actions:[`${svcPrefix[service]}:${actionsByService[service][0]}`],resource:'*',risk:'Medium',audited:'Never',active:true},...s.policies]}));setModal(null);say('Policy created and added to workspace')}}/>});
  const upload=(file?:File)=>{if(file){update(s=>({...s,policies:[{id:`POL-${Date.now()}`,name:file.name.replace(/\.(json|txt)$/i,''),user:users[0],service:'S3',actions:['s3:GetObject'],resource:'*',risk:'Medium',audited:'Never',active:true},...s.policies]}));say(`${file.name} imported as a local policy`)}};
 return <><PageHead eyebrow="IDENTITY GOVERNANCE / POLICY INVENTORY" title="IAM Policies" subtitle="Inspect granted permissions and scope across identities and cloud services." actions={<><label className="btn btn-secondary upload-btn"><Upload size={15}/>Upload policy<input type="file" accept=".json,.txt" onChange={e=>upload(e.target.files?.[0])} data-testid="input-upload-policy"/></label><Button onClick={()=>{update(s=>({...s,policies:makeState().policies}));say('Demo policy library restored')}} icon={<RefreshCw size={15}/>} testId="button-load-demo-policies">Load demo policies</Button><Button kind="primary" icon={<Plus size={15}/>} onClick={create} testId="button-create-policy">Create policy</Button></>}/>
  <div className="metrics-grid compact"><Metric label="Total policies" value={state.policies.length} change={`Across ${users.length} identities`} icon={FileCode2} testId="policies-total"/><Metric label="Wildcard policies" value={state.policies.filter(p=>p.actions.some(a=>a.endsWith('*'))||p.resource==='*').length} change="Action or resource wildcard" icon={AlertTriangle} tone="amber" testId="policies-wildcard"/><Metric label="High risk" value={state.policies.filter(p=>p.risk==='High'||p.risk==='Critical').length} change="Flagged by last audit" icon={ShieldAlert} tone="red" testId="policies-high-risk"/></div>
 <Panel className="data-panel"><div className="filters"><label className="table-search"><Search size={14}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Find a policy..." data-testid="input-policy-search"/></label><select value={risk} onChange={e=>setRisk(e.target.value)} data-testid="filter-policy-risk"><option>All risk</option>{['Critical','High','Medium','Low'].map(x=><option key={x}>{x}</option>)}</select><span className="filter-spacer"/><span className="dim">{rows.length} policies</span></div><TableWrap><thead><tr><th>POLICY</th><th>IDENTITY</th><th>SERVICE</th><th>PERMISSIONS</th><th>RESOURCE SCOPE</th><th>RISK</th><th>LAST AUDITED</th><th/></tr></thead><tbody>{rows.slice((page-1)*10,page*10).map(p=><tr key={p.id} data-testid={`row-policy-${p.id}`}><td><button className="table-primary" onClick={()=>open(p)} data-testid={`button-policy-detail-${p.id}`}>{p.name}</button><small className="table-sub mono">{p.id}</small></td><td>{p.user}</td><td><Badge>{p.service}</Badge></td><td className="mono">{p.actions.join(', ')}</td><td className="mono">{p.resource}</td><td><Badge tone={p.risk.toLowerCase()}>{p.risk}</Badge></td><td>{p.audited}</td><td><button className="icon-button small" onClick={()=>open(p)} aria-label="View policy" data-testid={`button-view-policy-${p.id}`}><ArrowUpRight size={14}/></button></td></tr>)}</tbody></TableWrap><Pager page={page} setPage={setPage} total={rows.length} size={10}/></Panel></>
}
function PolicyForm({onSave}:{onSave:(n:string,u:string,s:string)=>void}){const [name,setName]=useState(''),[user,setUser]=useState(users[0]),[service,setService]=useState('S3');return <form className="form-stack" onSubmit={e=>{e.preventDefault();if(name.trim())onSave(name.trim(),user,service)}}><label>Policy name<input required value={name} onChange={e=>setName(e.target.value)} placeholder="e.g. DataLakeReadOnly" data-testid="input-new-policy-name"/></label><label>Identity<select value={user} onChange={e=>setUser(e.target.value)} data-testid="select-new-policy-user">{users.map(u=><option key={u}>{u}</option>)}</select></label><label>Primary service<select value={service} onChange={e=>setService(e.target.value)} data-testid="select-new-policy-service">{services.map(u=><option key={u}>{u}</option>)}</select></label><p className="form-note">A starter policy document will be created locally. You can inspect it in the policy viewer.</p><Button kind="primary" testId="button-save-policy">Create policy</Button></form>}
function AuditPage({state,update,say,setLocation}:Ctx){
 const [running,setRunning]=useState(false),[step,setStep]=useState(-1),[complete,setComplete]=useState(false);
  const stages=['Load access logs','Parse IAM policies','Normalize permissions','Compare observed access','Detect permission risks','Generate recommendations','Compile evidence','Prepare audit report'];
  const run=()=>{if(running)return;setRunning(true);setComplete(false);setStep(0);let i=0;const timer=setInterval(()=>{i++;setStep(i);if(i>=stages.length){clearInterval(timer);setRunning(false);setComplete(true);update(s=>({...s,auditRuns:s.auditRuns+1,notifications:['Audit completed · '+new Date().toLocaleTimeString(),...s.notifications].slice(0,5)}));say(`Audit complete · ${state.findings.length} findings evaluated`)}},420)};
 return <><PageHead eyebrow="CONTINUOUS ASSURANCE / AUDIT ENGINE" title="Run IAM Security Audit" subtitle="Correlate observed access with granted IAM permissions to surface actionable risk." actions={<Badge tone="green"><span className="live-dot"/> ENGINE READY</Badge>}/>
 <div className="audit-layout"><Panel title="Audit workflow" sub="Analysis runs locally against the current workspace data" className="audit-workflow"><div className="workflow-meta"><span><Activity size={14}/> Scope</span><b>{state.logs.length.toLocaleString()} events <i/> {state.policies.length} policies</b><span><Clock3 size={14}/> Estimated duration <b>~4 sec</b></span></div><div className="steps">{stages.map((s,i)=><div key={s} className={`step ${i<step?'done':''} ${i===step&&running?'current':''} ${complete?'done':''}`}><div className="step-number">{i<step||complete?<Check size={14}/>:String(i+1).padStart(2,'0')}</div><span>{s}</span>{i===step&&running&&<i className="step-pulse"/>}</div>)}</div><div className="audit-controls"><Button kind="primary" icon={running?<span className="spinner"/>:<Play size={15}/>} disabled={running} onClick={run} testId="button-start-audit">{running?'Analyzing access patterns':'Run audit'}</Button><span className="dim">{running?`Step ${Math.min(step+1,stages.length)} of ${stages.length}`:'No changes will be made to cloud policies'}</span></div></Panel>
  <Panel title="Audit context" sub="Inputs included in this analysis"><div className="context-list">{[[Activity,'Access events',state.logs.length.toLocaleString(),'Last 90 days'],[FileCode2,'IAM policies',String(state.policies.length),'All active statements'],[Users,'Identities',String(users.length),'Human & workload'],[Globe2,'Environments','1','Production']].map(([I,l,v,d]:any)=><div key={l}><i><I size={15}/></i><span>{l}<small>{d}</small></span><b>{v}</b></div>)}</div><div className="assurance-note"><ShieldCheck size={16}/><span>Read-only analysis<small>Audit does not change your cloud configuration.</small></span></div></Panel></div>
 {complete&&<div className="audit-result fade-in"><div className="result-banner"><div className="success-mark"><Check size={20}/></div><div><b>Audit completed</b><small>Finished moments ago · Run #{state.auditRuns}</small></div><Badge tone="green">{(state.live?.least_privilege_score??87)<50?'AT RISK':'HEALTHY'} · {state.live?.least_privilege_score??87}/100</Badge></div><div className="result-metrics"><div><small>FINDINGS</small><b>{state.findings.length}</b></div><div><small>HIGH RISK</small><b>{state.findings.filter(f=>f.severity==='HIGH'||f.severity==='CRITICAL').length}</b></div><div><small>RECOMMENDATIONS</small><b>{state.recommendations.filter(r=>r.status==='Pending').length}</b></div><Button onClick={()=>setLocation('/findings')} testId="button-view-audit-findings">Review findings <ArrowRight size={14}/></Button></div></div>}</>
}
function FindingDetail({finding:f,state,goEvidence}:{finding:Finding;state:State;goEvidence:()=>void}){
 const matchingEvents=state.logs.filter(l=>l.user===f.user&&l.service===f.service&&`${svcPrefix[l.service]}:${l.action}`===f.permission).length;
 const observed=matchingEvents>0;
 const resolvedByUse=f.type==='UNUSED_PERMISSION'&&observed;
 return <div className="finding-detail">
  <div className="detail-meta"><Badge tone={f.severity.toLowerCase()}>{f.severity}</Badge><Badge>{f.type}</Badge><span>{f.id}</span></div>
  <div className="finding-callout"><ShieldAlert size={18}/><p>{resolvedByUse?`${matchingEvents} matching access event${matchingEvents===1?'':'s'} now confirm usage of this permission.`:observed?'Activity is observed, but this finding remains because the permission scope or operation is still a risk signal.':f.reason}</p></div>
  <div className="detail-summary"><div><small>IDENTITY</small><b>{f.user}</b></div><div><small>SERVICE</small><b>{f.service}</b></div><div><small>RISK SCORE</small><b>{f.score} / 100</b></div><div><small>CONFIDENCE</small><b>{f.confidence}%</b></div></div>
  <div className="permission-box"><small>GRANTED PERMISSION</small><code>{f.permission}</code><small>RESOURCE SCOPE</small><code>{f.resource}</code></div>
  <div className="why-box"><b>{resolvedByUse?'Why this finding was resolved':'Why this matters'}</b><p>{resolvedByUse?'A matching event is now present in the analysis window, so this unused-permission finding is resolved. The scenario data and evidence have been updated.':observed?'Usage alone does not remove a broad-scope or destructive-permission finding. Review the grant and resource boundary against the identity’s role.':'No matching event for this specific permission was found in the 90-day analysis window. Narrowing this grant reduces the potential impact of credential compromise.'}</p><small>Correlated against {state.logs.length.toLocaleString()} events · Analysis window 90 days</small></div>
  <Button kind="primary" icon={<FileSearch size={14}/>} onClick={goEvidence} testId="button-open-evidence">View evidence</Button>
 </div>;
}
function FindingsPage({state,openFinding,search}:Ctx){
 const [severity,setSeverity]=useState('All severities'),[type,setType]=useState('All types'),[status,setStatus]=useState('All statuses'),[sort,setSort]=useState('Risk score'),[page,setPage]=useState(1);
 const rows=useMemo(()=>state.findings.filter(f=>(!search||`${f.id} ${f.user} ${f.permission}`.toLowerCase().includes(search.toLowerCase()))&&(severity==='All severities'||f.severity===severity)&&(type==='All types'||f.type===type)&&(status==='All statuses'||f.status===status)).sort((a,b)=>sort==='Risk score'?b.score-a.score:sort==='Severity'?severities.indexOf(a.severity)-severities.indexOf(b.severity):a.id.localeCompare(b.id)),[state.findings,search,severity,type,status,sort]);
 const p=usePaged(rows,12);
 return <><PageHead eyebrow="DETECTION / PRIORITIZED RISK" title="Security Findings" subtitle="Investigate policy exposure with risk scoring, confidence, and explainable evidence." actions={<Button icon={<Download size={14}/>} onClick={()=>download('accessshield-findings.csv','id,severity,user,service,permission,resource,score,status\n'+rows.map(f=>`${f.id},${f.severity},${f.user},${f.service},${f.permission},${f.resource},${f.score},${f.status}`).join('\n'),'text/csv')} testId="button-export-findings">Export findings</Button>}/>
 <div className="metrics-grid compact"><Metric label="Open findings" value={state.findings.filter(f=>f.status==='Open').length} change="Actionable exposure" icon={ShieldAlert} tone="red" testId="finding-open-count"/><Metric label="Critical" value={state.findings.filter(f=>f.severity==='CRITICAL').length} change="Immediate attention" icon={AlertTriangle} tone="amber" testId="finding-critical-count"/><Metric label="In review" value={state.findings.filter(f=>f.status==='In review').length} change="Assigned to analysts" icon={Clock3} tone="purple" testId="finding-review-count"/></div>
 <Panel className="data-panel"><div className="filters"><span><SlidersHorizontal size={14}/> Refine findings</span><select value={severity} onChange={e=>setSeverity(e.target.value)} data-testid="filter-finding-severity"><option>All severities</option>{severities.map(x=><option key={x}>{x}</option>)}</select><select value={type} onChange={e=>setType(e.target.value)} data-testid="filter-finding-type"><option>All types</option>{findingTypes.map(x=><option key={x}>{x}</option>)}</select><select value={status} onChange={e=>setStatus(e.target.value)} data-testid="filter-finding-status"><option>All statuses</option>{['Open','In review','Resolved'].map(x=><option key={x}>{x}</option>)}</select><select value={sort} onChange={e=>setSort(e.target.value)} data-testid="sort-findings"><option>Risk score</option><option>Severity</option><option>Finding ID</option></select></div><TableWrap><thead><tr><th>SEVERITY</th><th>FINDING / PERMISSION</th><th>IDENTITY</th><th>SERVICE</th><th>RESOURCE</th><th>RISK</th><th>CONFIDENCE</th><th>STATUS</th></tr></thead><tbody>{p.items.map(f=><tr key={f.id} data-testid={`row-finding-${f.id}`}><td><Badge tone={f.severity.toLowerCase()}>{f.severity}</Badge></td><td><button className="table-primary mono" onClick={()=>openFinding(f)} data-testid={`button-finding-${f.id}`}>{f.permission}</button><small className="table-sub">{f.id} · {f.type}</small></td><td>{f.user}</td><td>{f.service}</td><td className="mono">{f.resource}</td><td><div className="score-cell"><b>{f.score}</b><span><i style={{width:`${f.score}%`}}/></span></div></td><td>{f.confidence}%</td><td><Badge tone={f.status==='Resolved'?'green':f.status==='In review'?'purple':'blue'}>{f.status}</Badge></td></tr>)}</tbody></TableWrap><Pager page={p.page} setPage={p.setPage} total={rows.length} size={p.size}/></Panel></>
}
function RecommendationsPage({state,update,say,setModal,search}:Ctx){
 const rows=state.recommendations.filter(r=>!search||`${r.id} ${r.user} ${r.service} ${r.current.join(' ')}`.toLowerCase().includes(search.toLowerCase()));
 const act=(id:string,status:string)=>{
  update(s=>{
   const recommendation=s.recommendations.find(r=>r.id===id);
   return {...s,
    recommendations:s.recommendations.map(r=>r.id===id?{...r,status}:r),
    policies:status==='Accepted'&&recommendation?s.policies.map(p=>p.id===recommendation.policyId?{...p,actions:recommendation.recommended,resource:recommendation.resource,risk:'Low',audited:'Just now'}:p):s.policies,
    notifications:[`Recommendation ${id} ${status.toLowerCase()}`,...s.notifications].slice(0,5)
   };
  });
  say(status==='Accepted'?'Recommendation accepted · policy updated locally':`Recommendation ${status.toLowerCase()}`);
 };
 const review=(r:Recommendation)=>setModal({title:`Review recommendation · ${r.id}`,body:<div className="finding-detail"><div className="recommend-diff"><div><small>CURRENT GRANT</small>{r.current.map(x=><code className="removed" key={x}>{x}</code>)}</div><ArrowRight/><div><small>RECOMMENDED</small>{r.recommended.map(x=><code className="retained" key={x}>{x}</code>)}</div></div><p>{r.reason}</p><div className="detail-summary"><div><small>RISK REDUCTION</small><b>{r.reduction}%</b></div><div><small>CONFIDENCE</small><b>{r.confidence}%</b></div><div><small>POLICY</small><b>{r.policyId}</b></div></div><div className="button-row"><Button kind="danger" onClick={()=>{act(r.id,'Rejected');setModal(null)}} testId={`button-reject-review-${r.id}`}>Reject</Button><Button kind="primary" onClick={()=>{act(r.id,'Accepted');setModal(null)}} testId={`button-accept-review-${r.id}`}>Accept recommendation</Button></div></div>});
 return <><PageHead eyebrow="REMEDIATION / LEAST PRIVILEGE" title="Recommendations" subtitle="Analyst-reviewed changes grounded in observed usage and policy context." actions={<Badge tone="purple"><Sparkles size={12}/> AI-assisted analysis</Badge>}/>
 <div className="recommend-summary"><div><small>PENDING REVIEW</small><b>{rows.filter(r=>r.status==='Pending').length}</b><span>recommendations</span></div><div className="summary-line"/><div><small>AVERAGE RISK REDUCTION</small><b>84.6<span>%</span></b><span>across pending changes</span></div><div className="summary-line"/><div><small>POLICIES IN SCOPE</small><b>{new Set(rows.map(r=>r.policyId)).size}</b><span>with suggested changes</span></div></div>
 <div className="recommend-list">{rows.slice(0,18).map(r=><article className="recommend-card panel" key={r.id} data-testid={`card-recommendation-${r.id}`}><div className="recommend-top"><div><span className="recommend-id">{r.id}</span><h3>{r.user} <i/> {r.service} <i/> <span>{r.policyId}</span></h3></div><Badge tone={r.status==='Accepted'?'green':r.status==='Rejected'?'red':'amber'}>{r.status}</Badge></div><div className="recommend-permissions"><div className="perm-col"><small>CURRENT PERMISSION</small>{r.current.map(p=><code className="removed" key={p}>{p}</code>)}</div><div className="perm-arrow"><ArrowRight size={17}/></div><div className="perm-col observed"><small>OBSERVED USAGE</small>{r.observed.map(p=><code key={p}>{p}</code>)}</div><div className="perm-arrow"><ArrowRight size={17}/></div><div className="perm-col target"><small>RECOMMENDED</small>{r.recommended.map(p=><code className="retained" key={p}>{p}</code>)}<code className="scope">Resource: {r.resource}</code></div><div className="rec-stats"><div><small>RISK CHANGE</small><b><span>HIGH</span><ArrowRight size={12}/><span className="green-text">LOW</span></b></div><div><small>REDUCTION</small><b className="green-text">{r.reduction}%</b></div><div><small>CONFIDENCE</small><b>{r.confidence}%</b></div></div></div><div className="recommend-bottom"><p><Sparkles size={13}/>{r.reason}</p><div><Button onClick={()=>review(r)} testId={`button-review-${r.id}`}>Review</Button>{r.status==='Pending'&&<><Button kind="quiet" onClick={()=>act(r.id,'Rejected')} testId={`button-reject-${r.id}`}>Reject</Button><Button kind="primary" onClick={()=>act(r.id,'Accepted')} testId={`button-accept-${r.id}`}>Accept</Button></>}</div></div></article>)}</div></>
}
function DiffPage({state,update,setLocation,say}:Ctx){
 const [selected,setSelected]=useState(state.recommendations[0]?.id??'');
 const rec=state.recommendations.find(r=>r.id===selected)??state.recommendations[0];const policy=state.policies.find(p=>p.id===rec?.policyId);const currentActionCount=rec?.current.some(a=>a.endsWith(':*'))?actionsByService[rec.service].length:rec?.current.length??0;
 const accept=()=>{if(!rec||rec.status==='Accepted')return;update(s=>{const recommendation=s.recommendations.find(r=>r.id===rec.id);if(!recommendation)return s;return {...s,policies:s.policies.map(p=>p.id===recommendation.policyId?{...p,actions:recommendation.recommended,resource:recommendation.resource,risk:'Low',audited:'Just now'}:p),recommendations:s.recommendations.map(r=>r.id===recommendation.id?{...r,status:'Accepted'}:r),notifications:[`Recommendation ${recommendation.id} accepted · policy updated`,...s.notifications].slice(0,5)}});say('Recommendation accepted · policy updated locally')};
 return <><PageHead eyebrow="CHANGE REVIEW / POLICY ANALYSIS" title="Policy Diff" subtitle="Compare current grants with an observed-usage recommendation before accepting change." actions={<Button icon={<Sparkles size={14}/>} kind="primary" onClick={()=>setLocation('/recommendations')} testId="button-review-recommendations">Review recommendations</Button>}/>
 <div className="diff-controls"><div><small>RECOMMENDATION</small><select value={selected} onChange={e=>setSelected(e.target.value)} data-testid="select-diff-recommendation">{state.recommendations.map(r=><option key={r.id} value={r.id}>{r.id} · {r.user} · {r.service}</option>)}</select></div><div className="diff-legend"><span><i className="red-dot"/>Removed access</span><span><i className="green-dot"/>Retained access</span><span><i className="blue-dot"/>Scope refined</span></div></div>
 {rec&&<><div className="diff-columns"><Panel title="Current policy" sub={`${policy?.name??rec.policyId} · ${rec.policyId}`} className="diff-card"><div className="diff-code-head"><Badge tone="red">CURRENT</Badge><span>IAM policy statement</span></div><div className="code-block"><pre><span className="json-muted">{'{\n  "Effect": '}</span><span className="json-value">"Allow"</span><span className="json-muted">{',\n  "Action": [\n'}</span>{rec.current.map((a,i)=><span key={a} className="code-removed">{`    "${a}"${i<rec.current.length-1?',':''}\n`}</span>)}<span className="json-muted">{'  ],\n  "Resource": '}</span><span className="code-removed">"*"</span><span className="json-muted">{'\n}'}</span></pre></div><div className="diff-summary-item"><span>Access granted</span><Badge tone="red">{rec.current.length} statements</Badge></div></Panel><div className="diff-middle"><div className="diff-arrow"><ArrowRight size={19}/></div><small>RECOMMEND</small><b>{rec.reduction}%</b><small>LESS EXPOSURE</small></div><Panel title="Recommended policy" sub="Based on 90 days of observed access" className="diff-card"><div className="diff-code-head"><Badge tone="green">PROPOSED</Badge><span>Least-privilege statement</span></div><div className="code-block"><pre><span className="json-muted">{'{\n  "Effect": '}</span><span className="json-value">"Allow"</span><span className="json-muted">{',\n  "Action": [\n'}</span>{rec.recommended.map((a,i)=><span key={a} className="code-retained">{`    "${a}"${i<rec.recommended.length-1?',':''}\n`}</span>)}<span className="json-muted">{'  ],\n  "Resource": '}</span><span className="code-scope">"{rec.resource}"</span><span className="json-muted">{'\n}'}</span></pre></div><div className="diff-summary-item"><span>Access retained</span><Badge tone="green">{rec.recommended.length} actions</Badge></div></Panel></div>
 <div className="diff-impact panel"><div><small>PERMISSIONS</small><b>{currentActionCount} <ArrowRight size={14}/> <span>{rec.recommended.length}</span></b></div><div><small>RESOURCE SCOPE</small><b>{policy?.resource??'*'} <ArrowRight size={14}/> <span className="scope-text">{rec.resource}</span></b></div><div><small>RISK POSTURE</small><b><Badge tone="red">{policy?.risk??'HIGH'}</Badge><ArrowRight size={14}/><Badge tone="green">LOW</Badge></b></div><div className="improvement"><span><CheckCircle2 size={16}/> Least-privilege improvement</span><b>{rec.reduction}%</b></div></div><div className="diff-actions"><span><LockKeyhole size={14}/> {rec.status==='Accepted'?'Policy updated in local workspace':'Policy changes require analyst approval'}</span>{rec.status==='Accepted'?<Badge tone="green">ACCEPTED</Badge>:<Button kind="primary" onClick={accept} testId="button-accept-diff">Accept proposed policy <Check size={14}/></Button>}</div></>}
  </>;
}
function EvidencePage({state,search}:Ctx){
 const candidates=state.findings.filter(f=>!search||`${f.user} ${f.permission} ${f.id}`.toLowerCase().includes(search.toLowerCase()));
 const [selected,setSelected]=useState(candidates[0]?.id??'');
 const f=candidates.find(x=>x.id===selected)??candidates[0];
 const identityEvents=f?state.logs.filter(l=>l.user===f.user&&l.service===f.service):[];
 const matchingEvents=f?identityEvents.filter(l=>`${svcPrefix[l.service]}:${l.action}`===f.permission):[];
 const permissionUsed=matchingEvents.length>0;
 const resolvedByUse=f?.type==='UNUSED_PERMISSION'&&permissionUsed;
 const observedPermissions=Array.from(new Set(identityEvents.map(l=>`${svcPrefix[l.service]}:${l.action}`)));
 const unobservedPermissions=f?actionsByService[f.service].map(a=>`${svcPrefix[f.service]}:${a}`).filter(a=>!observedPermissions.includes(a)):[];
 const history=Array.from({length:13},(_,i)=>{
  const from=Date.now()-(12-i)*7*86400000,to=from+7*86400000;
  return {week:i===12?'Now':`${84-i*7}d`,count:identityEvents.filter(l=>{const time=new Date(l.time).getTime();return time>=from&&time<to}).length};
 });
 return <>
  <PageHead eyebrow="EXPLAINABILITY / AUDIT TRAIL" title="Evidence & Explanation" subtitle="Trace the signals behind a finding. Every recommendation is grounded in observable evidence."/>
  <div className="evidence-selector"><div><small>SELECT FINDING</small><select value={f?.id??''} onChange={e=>setSelected(e.target.value)} data-testid="select-evidence-finding">{candidates.map(x=><option key={x.id} value={x.id}>{x.id} · {x.permission} · {x.user}</option>)}</select></div>{f&&<div className="evidence-selected"><Badge tone={f.severity.toLowerCase()}>{f.severity}</Badge><span>{f.id}</span><b>Confidence {f.confidence}%</b></div>}</div>
  {f&&<>
   <div className="evidence-main">
    <Panel title="Why was this permission flagged?" sub="Decision trace · policy-to-event correlation" className="evidence-explanation">
     <div className="evidence-perm"><div><small>PERMISSION UNDER REVIEW</small><code>{f.permission}</code></div><Badge tone={f.severity.toLowerCase()}>{f.score} RISK</Badge></div>
     <div className="checklist">
      <div className="check-row positive"><i><Check size={13}/></i><span><b>Permission granted by IAM policy</b><small>Found in {state.policies.find(p=>p.user===f.user&&p.service===f.service)?.name??'attached identity policy'}</small></span><span className="check-tag">CONFIRMED</span></div>
      <div className="check-row positive"><i><Check size={13}/></i><span><b>{permissionUsed?'Permission use is now observed':f.type==='DESTRUCTIVE_PERMISSION'?'Destructive operation':'Action exceeds observed scope'}</b><small>{permissionUsed?`${matchingEvents.length} matching event${matchingEvents.length===1?'':'s'} for this action`: 'Privilege is not required for the identity’s observed role'}</small></span><span className="check-tag">{permissionUsed?'IN USE':'RISK SIGNAL'}</span></div>
      <div className="check-row positive"><i><Check size={13}/></i><span><b>Resource scope is {f.resource}</b><small>Compare the granted resource with the identity’s observed activity.</small></span><span className="check-tag">REVIEW</span></div>
      <div className={`check-row ${permissionUsed?'positive':'negative'}`}><i>{permissionUsed?<Check size={13}/>:<X size={13}/>}</i><span><b>{permissionUsed?'Matching access event observed':'No matching access event'}</b><small>{permissionUsed?`${matchingEvents.length} matching ${f.permission} event${matchingEvents.length===1?'':'s'} found in the observation window`:`No matching ${f.permission} calls were found in the observation window`}</small></span><span className="check-tag">{permissionUsed?'OBSERVED':'UNUSED'}</span></div>
      <div className={`check-row ${permissionUsed?'positive':'negative'}`}><i>{permissionUsed?<Check size={13}/>:<X size={13}/>}</i><span><b>{permissionUsed?'Usage detected in analysis period':'No usage during analysis period'}</b><small>90-day lookback evaluated through {new Date().toLocaleDateString()}</small></span><span className="check-tag">90 DAYS</span></div>
     </div>
     <div className="evidence-conclusion"><Sparkles size={15}/><p><b>Conclusion</b>{resolvedByUse?'Matching activity now confirms use of this permission. The unused-access signal is cleared; review the remaining resource scope and policy breadth.':permissionUsed?'Activity is observed, but the finding still flags the permission scope or operation. Review the remaining risk signal.':`${f.reason} Replace with only observed actions and scope to a named resource.`}</p></div>
    </Panel>
    <Panel title="Evidence summary" sub="Observed activity for this identity">
     <div className="evidence-count"><span>Matching events</span><b>{matchingEvents.length}</b><small>in 90 days</small></div>
     <div className="evidence-count"><span>Identity events</span><b>{identityEvents.length}</b><small>across {f.service}</small></div>
     <div className="evidence-confidence"><div><span>Confidence</span><b>{f.confidence}%</b></div><div className="confidence-track"><i style={{width:`${f.confidence}%`}}/></div><small>High confidence · sufficient telemetry</small></div>
     <div className="access-split">
      <div><small>OBSERVED ACCESS</small>{observedPermissions.length?observedPermissions.slice(0,4).map(action=><code key={action}>{action}</code>):<code className="not-seen">No observed actions</code>}</div>
      <div><small>NOT OBSERVED</small>{unobservedPermissions.length?unobservedPermissions.slice(0,4).map(action=><code className="not-seen" key={action}>{action}</code>):<code>No other actions</code>}</div>
     </div>
    </Panel>
   </div>
   <Panel title="90-day activity timeline" sub={`Observed calls to ${f.service} by ${f.user}`} className="timeline-panel"><div className="timeline-chart"><ResponsiveContainer width="100%" height="100%"><BarChart data={history} margin={{top:12,right:10,left:-24,bottom:0}}><CartesianGrid stroke="#1b3152" strokeDasharray="3 5" vertical={false}/><XAxis dataKey="week" stroke="#61738d" tick={{fontSize:10}} axisLine={false} tickLine={false}/><YAxis stroke="#61738d" tick={{fontSize:10}} axisLine={false} tickLine={false}/><ChartTooltip contentStyle={{background:'#0a1428',border:'1px solid #1b3152',borderRadius:8}}/><Bar dataKey="count" fill="#168bff" radius={[3,3,0,0]}/></BarChart></ResponsiveContainer></div><div className="timeline-foot"><span><i className="blue-dot"/>Observed service activity</span><span>90 days ago <ArrowRight size={12}/> Today</span></div></Panel>
  </>}
 </>;
}
function SimulatorPage({state,update,say}:Ctx){
 const [user,setUser]=useState('Alice Chen'),[service,setService]=useState('S3'),[action,setAction]=useState('DeleteObject'),[resource,setResource]=useState('company-data/file.csv');
 const [scenarioEvent,setScenarioEvent]=useState<Log|null>(null),[resolvedByEvent,setResolvedByEvent]=useState(0),[baselineUsed,setBaselineUsed]=useState(false);
 const currentPolicy=state.policies.find(p=>p.user===user&&p.service===service);
 const identityEvents=state.logs.filter(l=>l.user===user&&l.service===service);
 const observedActions=Array.from(new Set(identityEvents.map(l=>`${svcPrefix[l.service]}:${l.action}`)));
 const full=`${svcPrefix[service]}:${action}`;
 const used=observedActions.includes(full);
 const scenarioMatchesSelection=!!scenarioEvent&&scenarioEvent.user===user&&scenarioEvent.service===service&&scenarioEvent.action===action;
 const grantedActions=currentPolicy?.actions.includes(`${svcPrefix[service]}:*`)?actionsByService[service]:currentPolicy?actionsByService[service].filter(a=>currentPolicy.actions.includes(`${svcPrefix[service]}:${a}`)):actionsByService[service];
 const observedGranted=grantedActions.filter(a=>observedActions.includes(`${svcPrefix[service]}:${a}`)).length;
 const usedPercent=grantedActions.length?Math.round(observedGranted/grantedActions.length*100):0,unusedPercent=100-usedPercent;
 const overbroadPercent=currentPolicy&&(currentPolicy.resource==='*'||currentPolicy.actions.some(a=>a.endsWith('*')))?10:0;
 const coveragePercent=Math.round(new Set(state.logs.map(l=>`${svcPrefix[l.service]}:${l.action}`)).size/(services.reduce((n,s)=>n+actionsByService[s].length,0))*100);
 const currentFindings=state.findings.filter(f=>f.status==='Open').length;
 const impactResolved=scenarioMatchesSelection?resolvedByEvent:0,beforeFindings=currentFindings+impactResolved;
 const currentRiskScore=82,afterRiskScore=Math.max(0,currentRiskScore-impactResolved*11);
 const latestTime=state.logs.reduce((latest,l)=>Math.max(latest,new Date(l.time).getTime()),0);
 const add=()=>{
  const ev:Log={id:Date.now(),time:new Date().toISOString(),user,service,action,resource,status:'SUCCESS',region:'us-east-1'};
  const newlyResolved=state.findings.filter(f=>f.type==='UNUSED_PERMISSION'&&f.status==='Open'&&f.user===user&&f.service===service&&f.permission===full).length;
  setBaselineUsed(used);setResolvedByEvent(newlyResolved);setScenarioEvent(ev);
  update(s=>({...s,logs:[ev,...s.logs],eventsAdded:s.eventsAdded+1,findings:s.findings.map(f=>f.type==='UNUSED_PERMISSION'&&f.user===user&&f.service===service&&f.permission===full?{...f,status:'Resolved'}:f),recommendations:s.recommendations.map(r=>r.user===user&&r.service===service?{...r,observed:Array.from(new Set([...r.observed,full])),recommended:Array.from(new Set([...r.recommended,full]))}:r),notifications:[`Scenario event added · ${user} · ${full}`,...s.notifications].slice(0,5)}));
  say(`${full} is now observed · risk re-evaluated`);
 };
 const reset=()=>{const baseline=makeState();update(()=>({...baseline,auditRuns:state.auditRuns}));setScenarioEvent(null);setResolvedByEvent(0);setBaselineUsed(false);setAction('DeleteObject');setService('S3');setUser('Alice Chen');setResource('company-data/file.csv');say('Scenario reset to baseline dataset')};
 return <>
  <PageHead eyebrow="WHAT-IF ANALYSIS / INTERACTIVE DEMO" title="IAM Scenario Simulator" subtitle="Change user activity and see how AccessShield X adapts in real time." actions={<Badge tone="purple"><Sparkles size={12}/> SAMPLE SIMULATION (LOCAL)</Badge>}/>
  <LiveScenario/><div className="sim-stage"><div className="sim-stage-copy"><span>SCENARIO CONTROL</span><h2>Activity changes the risk picture.</h2><p>Add an observed access event to recalculate findings, recommendations, and evidence instantly.</p><div className="sim-data-chips"><span><Activity size={13}/>{state.logs.length.toLocaleString()} events</span><span><ShieldAlert size={13}/>{currentFindings} open findings</span><span><Sparkles size={13}/>{state.recommendations.filter(r=>r.status==='Pending').length} pending recommendations</span></div></div><div className="sim-emblem"><img src="/accessshield-mark.png" alt="" /></div></div>
  <div className="sim-grid">
   <Panel title="Add observed access event" sub="Event is added to local dataset and re-analyzed">
    <div className="form-stack sim-form">
     <label>Identity<select value={user} onChange={e=>setUser(e.target.value)} data-testid="select-sim-user">{users.map(u=><option key={u}>{u}</option>)}</select></label>
     <label>Cloud service<select value={service} onChange={e=>{setService(e.target.value);setAction(actionsByService[e.target.value][0])}} data-testid="select-sim-service">{services.map(s=><option key={s}>{s}</option>)}</select></label>
     <label>Action<select value={action} onChange={e=>setAction(e.target.value)} data-testid="select-sim-action">{actionsByService[service].map(a=><option key={a}>{a}</option>)}</select></label>
     <label>Resource<input value={resource} onChange={e=>setResource(e.target.value)} data-testid="input-sim-resource"/></label>
     <div className="sim-form-buttons"><Button kind="primary" icon={<Zap size={15}/>} onClick={add} testId="button-add-event">Add event & re-analyze</Button><Button kind="quiet" icon={<RefreshCw size={14}/>} onClick={reset} testId="button-reset-scenario">Reset scenario</Button></div>
     <small className="form-note"><LockKeyhole size={12}/> Simulated locally only · no cloud actions are performed</small>
    </div>
   </Panel>
   <Panel title="Permission state" sub="Policy and usage for selected identity">
    <div className="sim-policy">
     <div><small>CURRENT USER</small><b>{user}</b></div>
     <div><small>CURRENT POLICY</small><code>{currentPolicy?currentPolicy.actions.join(', '):'No matching policy'}</code></div>
     <div><small>OBSERVED ACCESS</small><div className="chips">{observedActions.slice(0,4).map(x=><code key={x}>{x}</code>)}{!observedActions.length&&<code className="not-seen">No observed actions</code>}</div></div>
     <div className={`unused-permission ${used?'used':''}`}><div><code>{full}</code><Badge tone={!currentPolicy?'red':used?'green':'amber'}>{!currentPolicy?'NO POLICY':used?'USED':'UNUSED'}</Badge></div><small>{!currentPolicy?'No matching policy was found for this identity and service.':used?`${identityEvents.filter(l=>l.action===action).length} matching access event(s) are present in the analysis window.`:'Granted by policy, but no matching event was seen in 90 days.'}</small></div>
    </div>
   </Panel>
  </div>
  <div className="before-after"><div className="ba-label"><span>LIVE IMPACT</span><ArrowRight size={16}/></div><div className="ba-cards">
   <div className="ba-card before"><small>BEFORE</small><b>{beforeFindings}</b><span>open findings</span><div><ShieldAlert size={14}/>Risk score <strong>{currentRiskScore}/100</strong></div><small className="ba-perm">{full} <Badge tone={scenarioMatchesSelection&&!baselineUsed?'amber':used?'green':'amber'}>{scenarioMatchesSelection?(baselineUsed?'USED':'UNUSED'):(used?'USED':'UNUSED')}</Badge></small></div>
   <div className="ba-transition"><div><ArrowRight size={17}/></div><span>{scenarioMatchesSelection?'EVENT SIMULATED':scenarioEvent?'MOST RECENT EVENT':'AWAITING EVENT'}</span></div>
   <div className={`ba-card after ${scenarioMatchesSelection&&resolvedByEvent?'changed':''}`}><small>AFTER</small><b>{currentFindings}</b><span>open findings</span><div><ShieldCheck size={14}/>Risk score <strong>{afterRiskScore}/100</strong></div><small className="ba-perm">{full} <Badge tone={used?'green':currentPolicy?'amber':'red'}>{!currentPolicy?'NO POLICY':used?'USED':'UNUSED'}</Badge></small></div>
   <div className="ba-insight"><Sparkles size={17}/><div><b>{scenarioEvent?(scenarioMatchesSelection?'Risk recalculated':'Showing current selection'):'Awaiting simulation'}</b><p>{scenarioEvent?`Last simulated: ${scenarioEvent.user} · ${svcPrefix[scenarioEvent.service]}:${scenarioEvent.action}. ${scenarioMatchesSelection?`${full} is ${used?'now used':'still unused'}; findings, recommendations, and evidence reflect the event.`:'Select the event identity, service, and action to inspect its effect.'} ${state.logs.length.toLocaleString()} events in the local dataset.`:'Add an event to see a live comparison of the least-privilege posture.'}</p></div></div>
  </div></div>
  <div className="sim-charts">
   <Panel title="Permission usage" sub="Observed actions / current grants"><div className="sim-usage"><div className="usage-ring"><svg viewBox="0 0 100 100"><circle cx="50" cy="50" r="40"/><circle cx="50" cy="50" r="40" style={{strokeDasharray:`${usedPercent*2.51} 251`}}/></svg><div><b>{usedPercent}%</b><small>IN USE</small></div></div><div className="usage-numbers"><span>Used permissions <b>{usedPercent}%</b></span><i><b style={{width:`${usedPercent}%`}}/></i><span>Unused permissions <b>{unusedPercent}%</b></span><i><b className="unused-bar" style={{width:`${unusedPercent}%`}}/></i><span>Overbroad access <b>{overbroadPercent}%</b></span><i><b className="over-bar" style={{width:`${overbroadPercent}%`}}/></i></div></div></Panel>
   <Panel title="Evidence coverage" sub="Observed action-to-grant coverage"><div className="evidence-tile"><div className="evidence-tile-number"><b>{state.logs.length.toLocaleString()}</b><small>events analyzed</small></div><div className="coverage-track"><i style={{width:`${coveragePercent}%`}}/></div><div className="coverage-foot"><span>Coverage</span><b>{coveragePercent}%</b></div><div className="last-event"><Clock3 size={13}/>{latestTime?`Latest event · ${new Date(latestTime).toLocaleString()}`:'No events in the dataset'}</div></div></Panel>
  </div>
 </>;
}
function ReportsPage({state,say}:Ctx){
 const [generated,setGenerated]=useState(false);const top=state.recommendations.slice(0,4);
 const json=()=>({product:'AccessShield X',report:'IAM Audit Report',generatedAt:new Date().toISOString(),summary:{policies:state.policies.length,users:users.length,accessEvents:state.logs.length,findings:state.findings.length,highRisk:state.findings.filter(f=>f.severity==='HIGH'||f.severity==='CRITICAL').length},findings:state.findings,recommendations:state.recommendations});
 const exportCsv=()=>{download('accessshield-iam-audit.csv','id,severity,user,service,permission,resource,risk_score,status\n'+state.findings.map(f=>[f.id,f.severity,f.user,f.service,f.permission,f.resource,f.score,f.status].join(',')).join('\n'),'text/csv');say('CSV report exported')};
 return <><PageHead eyebrow="GOVERNANCE / AUDIT OUTPUT" title="Audit Reports" subtitle="Generate an executive-ready snapshot of current IAM exposure and remediation posture." actions={<Button kind="primary" icon={<FileBarChart2 size={15}/>} onClick={()=>{setGenerated(true);say('Report generated with current workspace data')}} testId="button-generate-report">Generate report</Button>}/>
 <div className="report-actions panel"><div className="report-action-title"><i><Download size={17}/></i><div><b>Export report</b><small>Download a portable copy or print to PDF.</small></div></div><div><Button onClick={()=>window.print()} icon={<Download size={14}/>} testId="button-download-pdf">Download PDF</Button><Button onClick={exportCsv} icon={<Download size={14}/>} testId="button-export-csv">Export CSV</Button><Button onClick={()=>{download('accessshield-iam-audit.json',JSON.stringify(json(),null,2),'application/json');say('JSON report exported')}} icon={<Download size={14}/>} testId="button-export-json">Export JSON</Button></div></div>
  <article className="report-preview panel" data-testid="report-preview"><div className="report-brand"><div><img src="/accessshield-mark.png" alt="" /><b>ACCESS<span>SHIELD</span> X</b></div><Badge tone={generated?'green':'blue'}>{generated?'GENERATED':'PREVIEW'}</Badge></div><div className="report-title"><div><small>SECURITY ASSESSMENT · {new Date().getFullYear()}</small><h2>IAM Audit Report</h2><p>Least-privilege posture assessment for Northstar Labs</p></div><div className="report-date"><small>AUDIT DATE</small><b>{new Date().toLocaleDateString('en-US',{year:'numeric',month:'long',day:'numeric'})}</b><span>Environment · Production</span></div></div><div className="report-summary"><h3>Executive summary</h3><p>AccessShield X analyzed identity permissions against observed cloud activity over a 90-day period. The assessment identified overbroad grants and unused permissions across five cloud services. Recommendations are ranked by risk reduction and confidence.</p></div><div className="report-kpis"><div><small>TOTAL POLICIES</small><b>{state.policies.length}</b></div><div><small>TOTAL USERS</small><b>{users.length}</b></div><div><small>ACCESS EVENTS</small><b>{state.logs.length.toLocaleString()}</b></div><div><small>FINDINGS</small><b>{state.findings.length}</b></div><div><small>HIGH RISK</small><b className="red-text">{state.findings.filter(f=>f.severity==='HIGH'||f.severity==='CRITICAL').length}</b></div></div><div className="report-two-col"><div><h3>Risk distribution</h3>{severities.map((s,i)=><div className="report-risk" key={s}><span><i className={`sev-${s.toLowerCase()}`}/>{s}</span><b>{state.findings.filter(f=>f.severity===s).length}</b></div>)}<div className="report-risk"><span>Unused permissions</span><b>{state.findings.filter(f=>f.type==='UNUSED_PERMISSION').length}</b></div><div className="report-risk"><span>Overbroad permissions</span><b>{state.findings.filter(f=>f.type==='OVERBROAD_PERMISSION').length}</b></div></div><div><h3>Top recommendations</h3>{top.map(r=><div className="report-rec" key={r.id}><div><b>{r.user} · {r.service}</b><small>{r.current[0]} → {r.recommended[0]}</small></div><Badge tone="green">-{r.reduction}%</Badge></div>)}</div></div><div className="report-footer"><ShieldCheck size={15}/>Evidence-backed analysis · {state.logs.length} events correlated · Generated by AccessShield X</div></article></>
}
function SettingsPage({say}:Ctx){
 const [org,setOrg]=useState(()=>localStorage.getItem('asx-org')||'Northstar Labs'),[lookback,setLookback]=useState('90 days'),[critical,setCritical]=useState(85),[high,setHigh]=useState(65),[digest,setDigest]=useState(true),[notify,setNotify]=useState(true),[role,setRole]=useState('ADMIN');
 const save=()=>{localStorage.setItem('asx-org',org);localStorage.setItem('asx-config',JSON.stringify({lookback,critical,high,digest,notify,role}));say('Workspace settings saved locally')};
 return <><PageHead eyebrow="WORKSPACE / CONFIGURATION" title="Settings" subtitle="Configure workspace context, audit behavior, risk thresholds, and analyst notifications." actions={<Button kind="primary" icon={<Check size={14}/>} onClick={save} testId="button-save-settings">Save changes</Button>}/>
 <div className="settings-layout"><div className="settings-nav">{[['Organization','Workspace identity'],['Audit configuration','Analysis window'],['Risk thresholds','Severity scoring'],['Notifications','Analyst alerts'],['Integrations','Connected telemetry']].map(([x,y],i)=><a href={`#settings-${i}`} key={x} onClick={e=>{e.preventDefault();document.getElementById(`settings-${i}`)?.scrollIntoView({behavior:'smooth'})}} data-testid={`settings-nav-${i}`}><b>{x}</b><small>{y}</small></a>)}</div><div className="settings-sections"><Panel title="Organization" sub="Workspace profile and analyst role" className="settings-panel" ><div id="settings-0" className="settings-form-grid"><label>Organization name<input value={org} onChange={e=>setOrg(e.target.value)} data-testid="input-organization-name"/></label><label>Workspace region<select defaultValue="us-east-1" data-testid="select-workspace-region"><option>us-east-1</option><option>us-west-2</option><option>eu-west-1</option></select></label><label>Default analyst role<select value={role} onChange={e=>setRole(e.target.value)} data-testid="select-user-role">{['ADMIN','AUDITOR','VIEWER'].map(x=><option key={x}>{x}</option>)}</select></label><div className="settings-info"><Users size={14}/><span>Role-based controls are preview-only in this demo.<small>Current role: {role}</small></span></div></div></Panel>
 <Panel title="Audit configuration" sub="Define the observation window and analysis coverage" className="settings-panel"><div id="settings-1" className="settings-form-grid"><label>Observation lookback<select value={lookback} onChange={e=>setLookback(e.target.value)} data-testid="select-lookback">{['30 days','60 days','90 days','180 days'].map(x=><option key={x}>{x}</option>)}</select></label><label>Audit schedule<select defaultValue="Daily" data-testid="select-audit-schedule"><option>Daily</option><option>Weekly</option><option>On demand</option></select></label><div className="settings-info"><ShieldCheck size={14}/><span>Read-only audit mode<small>No cloud permissions are modified automatically.</small></span><b className="green-text">ENABLED</b></div></div></Panel>
 <Panel title="Risk thresholds" sub="Minimum score used to classify findings" className="settings-panel"><div id="settings-2" className="range-list"><label><span>Critical risk <b>{critical}</b></span><input type="range" min="70" max="100" value={critical} onChange={e=>setCritical(+e.target.value)} data-testid="range-critical-threshold"/><small>Scores at or above this value are marked critical.</small></label><label><span>High risk <b>{high}</b></span><input type="range" min="40" max="84" value={high} onChange={e=>setHigh(+e.target.value)} data-testid="range-high-threshold"/><small>Scores at or above this value are marked high.</small></label></div></Panel>
 <Panel title="Notifications" sub="Choose which analyst updates appear in the workspace" className="settings-panel"><div id="settings-3" className="toggle-list"><Toggle label="High-risk finding alerts" detail="Notify when a critical or high-risk permission is detected." value={notify} onChange={setNotify} testId="toggle-high-risk"/><Toggle label="Audit completion digest" detail="Show a summary after each scheduled audit run." value={digest} onChange={setDigest} testId="toggle-audit-digest"/></div></Panel>
 <Panel title="Integrations" sub="Local demo telemetry sources" className="settings-panel"><div id="settings-4" className="integration-row"><div className="integration-icon"><CloudUpload size={18}/></div><div><b>CloudTrail · Production</b><small>Sample telemetry connected · {role==='VIEWER'?'Read only':'Healthy'}</small></div><Badge tone="green">CONNECTED</Badge><Button onClick={()=>say('CloudTrail source settings opened')} testId="button-configure-cloudtrail">Configure</Button></div><div className="integration-row"><div className="integration-icon"><FileCode2 size={18}/></div><div><b>IAM policy inventory</b><small>{role==='ADMIN'?'Local demo source':'Read-only snapshot'} · Last sync just now</small></div><Badge tone="green">HEALTHY</Badge><Button onClick={()=>say('Policy inventory refreshed')} testId="button-refresh-inventory">Refresh</Button></div></Panel></div></div></>
}
function Toggle({label,detail,value,onChange,testId}:{label:string;detail:string;value:boolean;onChange:(v:boolean)=>void;testId:string}){return <div className="toggle-row"><span><b>{label}</b><small>{detail}</small></span><button className={`switch ${value?'on':''}`} onClick={()=>onChange(!value)} role="switch" aria-checked={value} data-testid={testId}><i/></button></div>}

export default App;
